name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install R dependencies
        run: |
          install.packages(c("rmarkdown", "knitr", "networkD3", "dplyr", "plotly", 
                           "htmlwidgets", "DiagrammeR", "DiagrammeRsvg", "rsvg", 
                           "webshot", "htmltools", "svglite"))
        shell: Rscript {0}

      - name: Render R Markdown
        run: |
          rmarkdown::render("agentic_context_analysis.Rmd", output_format = "html_document")
        shell: Rscript {0}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
